config/routes.rb
TwitterForZombies::Application.routes.draw do

  resources :tweet
  resources :zombie
  resources :sessions
  root :to => "sessions#index"

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  attr_accessible :status, :zombie

  belongs_to :zombie

  #validates_presence_of :status, :zombie

end

app/models/zombie.rb
class Zombie < ActiveRecord::Base
  attr_accessible :graveyard, :name

  has_many :tweets, dependent: :destroy

  #validates_prescence_of :name, :graveyard

  def create_tweets
    t1 = Tweet.create(status: 'Hello', zombie: self)
  	tweets << t1
  end

  def number_of_tweets
  	tweets.count
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		session[:zombie] = nil
		redirect_to sessions_path
	end

	def create
		@current_zombie = Zombie.find_by_name(params[:session][:name])
  		if !@current_zombie.nil?
  			session[:zombie] = @current_zombie
      		redirect_to @current_zombie
  		else
			flash.now[:error] = 'Zombie not found!'
			render 'login_fail'
		end	
	end

	def destroy
		
	end

end

app/controllers/tweet_controller.rb
class TweetController < ApplicationController
  def show
  	@tweet = Tweet.find(params[:id])

    respond_to do |format|
      format.html
      format.json {render :json => @tweet}
    end

  end

  def index
  	@tweets = Tweet.all
    respond_to do |format|
      format.html
      format.json {render :json => @tweets}
    end
  end

  def new
  	@tweet = Tweet.new
  end

  def create
  	t = Tweet.create(params[:tweet])
    t.zombie = session[:zombie]
    t.save
  	redirect_to tweet_index_path
  end
end

app/controllers/zombie_controller.rb
class ZombieController < ApplicationController

  def show
  	@zombie = Zombie.find(params[:id])
  end

  def index
  	@zombies = Zombie.all
  end

  def new
  	@zombie = Zombie.new
  end

  def create
  	zombie = Zombie.create(params[:zombie])
    session[:zombie] = zombie
  	redirect_to zombie_index_path
  end

  def edit
      # @zombie = session[:zombie]
    @update_zombie = Zombie.find(params[:id])
    # @update_zombie.name = params[:name]
    # @update_zombie.graveyard = params[:graveyard]
    
    # @update_zombie.save
  end

  def update
    update_zombie = Zombie.find(params[:id])
    # update_zombie.update_attributes(
    #   :name => params[:name],
    #   :graveyard => params[:graveyard]
    #   )
    update_zombie.attributes = params[:zombie]
    update_zombie.save
    # update_zombie.name = params[:name]
    # update_zombie.graveyard = params[:graveyard]
    
    # update_zombie.save

    redirect_to zombie_path

  end

  def destroy
    zombie = Zombie.find(params[:id])
    zombie.destroy
    redirect_to tweets_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>



<html>


<head>
  <title>TwitterForZombies</title>
  <%= javascript_include_tag "jquery-1.7.2.min" %>
  <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
  <%= stylesheet_link_tag    "zombie", :media => "all" %>
  <%= javascript_include_tag "bootstrap" %>
  <%= javascript_include_tag "bootstrap-dropdown" %>
<!--   <%= image_tag "glyphicons-halflings.png" %>
  <%= image_tag "glyphicons-halflings-white.png" %> -->
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
	    <div class="container">
	    	<a class="brand">
  				Twitter for Zombies
			</a>
			<ul class="nav">
				<li class="divider-vertical"></li>
				<li><%= link_to 'All Zombies', zombie_index_path %></li>
				<li class="divider-vertical"></li>
				<li><%= link_to 'All Tweets', tweet_index_path %></li>
				<li class="divider-vertical"></li>
			</ul>
	    	<div class="pull-right">
				<% if session[:zombie].nil? %>
					<button class = "btn"><%= link_to "Log In!", sessions_path %></button>
					<%= link_to "Sign up!", new_zombie_path %>
				<% else %>
					
					<div class="btn-group">
						<button class="btn">
							<!-- <i class="icon-user" ></i> -->
							<%= link_to session[:zombie].name, session[:zombie] %>
						</button>
						<button class="btn dropdown-toggle" data-toggle="dropdown">
						<span class="caret"></span>
						</button>
						<ul class="dropdown-menu">
							<li><%= link_to 'Home', session[:zombie] %></li>
						    <li><%= link_to 'New Tweet', new_tweet_path %></li>
						    <li><%= link_to 'Edit Account', edit_zombie_path(session[:zombie]) %></li>
						    <li class="divider"></li>
						    <li><%= link_to 'Log Out!', new_session_path%></li>
						</ul>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>
<div class="navbar navbar-fixed-bottom">
	<div class="navbar-inner">
	    <div class="container">
	    	<form class="navbar-search pull-right">
  				<input type="text" class="search-query" placeholder="Search">
			</form>
	    </div>
	</div>	
</div>



<%= yield %>

<!-- 	<br /><br />

	<% if session[:zombie].nil?%>
		<button class = "btn"><%= link_to "Log In!", sessions_path %></button>
	<% else %>
		<button class = "btn"><%= link_to "Log Out!", new_session_path%></button>
	<% end %> -->

</body>
<script type = "text/javascript">
	$('.dropdown-toggle').dropdown();
</script>
</html>

app/views/tweet/index.html.erb
<div class="container">	
	<div class="margin_offset">

		Number of Tweets = <%= @tweets.count %> <br />

		<table class="table table-striped table-bordered table-condensed">
		<tr>
		<th>ID</th>
		<th>Status</th>
		<th>Zombie Name</th>
		<th>zombie ID</th>
		<th>Created At</th>

		</tr>

		<% @tweets.each do |tweet| %>
			<tr>
			<td><%= link_to tweet.id, tweet %></td>
			<td><%= tweet.status %></td>
			<% if tweet.zombie !nil %>
				<td><%= tweet.zombie.name %></td>
			<% else %>
				<td><%= ' ' %></td>
			<% end %>
			<td><%= link_to tweet.zombie_id, tweet.zombie %></td>
			<td><%= tweet.created_at %></td>
			</tr>
		<% end %>

		</table>

	</div>
</div>

app/views/tweet/new.html.erb
<div class="container">
	<%= form_for @tweet, :url => {:action => :create} do |f| %>
		<div class="margin_offset">
		
		<% if session[:zombie].nil? %>
			You must be logged in to post a tweet! <%= link_to "Log In", sessions_path %>
			<br /><br />	
			
		<% else %>
			Status: <br />
			<%= f.text_area :status, :cols => 35, :rows => 5, :width => '300', :maxlength => 140 %> <br />

			<button class = "btn">Submit Tweet!<% f.submit %></button>
		<% end %>

		</div>
	<% end %>
</div>

app/views/tweet/show.html.erb
<div class="container">
	<div class="margin_offset">
		<table class="table table-striped table-bordered table-condensed">
		<tr>
		<th>ID</th>
		<th>Status</th>
		<th>Zombie Name</th>
		<th>Created At</th>
		</tr>
		<tr>
		<td><%= @tweet.id %></td>
		<td><%= @tweet.status %></td>
		<% if @tweet.zombie !nil %>
				<td><%= @tweet.zombie.name %></td>
			<% else %>
				<td><%= ' ' %></td>
			<% end %>
		<td><%= @tweet.created_at %></td>
		</tr>
		</table>

	</div>
</div>

app/views/zombie/delete.html.erb
<div class="container">
	
	<div class="margin_offset">
		
		Are you sure you want to delete your zombie? <%= link_to 'Yes, delete my Zombie', delete_zombie_path %>
		
	</div>	
</div>

app/views/zombie/edit.html.erb
<div class="container">
	
	<%= form_for @update_zombie, :url => {:action => :update} do |f| %>
	<div class="margin_offset">
		
		<% if @update_zombie == session[:zombie]  %>
			Change Name: <br />
			<%= f.text_field :name, :maxlength => 15 %> <br />
			Change Graveyard: <br />
			<%= f.text_field :graveyard, :maxlength => 20 %> <br />

			<button class = "btn">Update Zombie!<% f.submit %></button>

	
		<% else %>
			You cannot edit another person's zombie!
		<% end %>

	</div>

	<% end %>
</div>

app/views/zombie/index.html.erb
<div class="container">	
	<div class="margin_offset">
		Number of Zombies = <%= @zombies.count %> <br />

		<table class="table table-striped table-bordered table-condensed">
		<tr>
		<th>ID</th>
		<th>Name</th>
		<th>Graveyard</th>
		<th>Most Recent Tweet</th>
		<th>Number of Tweets</th>
		<th>Created At</th>
		</tr>

		<% @zombies.each do |zombie| %>
			<tr>
			<td><%= link_to zombie.id, zombie %></td>
			<td><%= zombie.name %></td>
			<td><%= zombie.graveyard %></td>
			<% if zombie.tweets.count > 0 %>
				<td><%= zombie.tweets.last.status %></td>
			<% else %>	
				<td><%= ' ' %></td>
			<% end %>
			<td><%= zombie.tweets.count %></td>
			<td><%= zombie.created_at %></td>
			</tr>
		<% end %>

		</table>

	</div>
</dic>

app/views/zombie/new.html.erb
<div class="container">

	<%= form_for @zombie, :url => {:action => :create} do |f| %>
	<div class="margin_offset">
		
		<% if session[:zombie].nil? %>
			Name: <br />
			<%= f.text_field :name, :maxlength => 15 %> <br />
			Graveyard: <br />
			<%= f.text_field :graveyard, :maxlength => 20 %> <br />

			<button class = "btn">Create Zombie!<% f.submit %></button>
		<% else %>
			You cannot create a new Zombie if you are currently logged in.
		<% end %>

	</div>

	<% end %>
</div>

app/views/zombie/show.html.erb
<div class="container">
	<div class="margin_offset">
		<table class="table table-striped table-bordered table-condensed">
		<tr>
		<th>ID</th>
		<th>Name</th>
		<th>Graveyard</th>
		<th>Most Recent Tweet </th>
		<th>Number of Tweets</th>
		<th>Created At</th>
		</tr>
		<tr>
		<td><%= @zombie.id %></td>
		<td><%= @zombie.name %></td>
		<td><%= @zombie.graveyard %></td>
		<% if @zombie.tweets.count > 0 %>
			<td><%= @zombie.tweets.last.status %></td>
		<% else %>
			<td><%= ' ' %></td>
		<% end %>
		<td><%= @zombie.tweets.count %></td>
		<td><%= @zombie.created_at %></td>
		</tr>
		</table>

		<% if @zombie == session[:zombie]%>

			<%= form_for(:tweet, :tweet => {:action => :create}) do |f| %>
					
				Status: <br />
				<%= f.text_area :status, :cols => 35, :rows => 5, :width => '300', :maxlength => 140 %> <br />

				<button class = "btn">Submit Tweet!<% f.submit %></button>
			<% end %>
		<% end %>

		<% if @zombie.tweets.count > 0 %>
			<br /><br />
			All of <%= @zombie.name %>'s Tweets
			<table class="table table-striped table-bordered table-condensed">
			<tr>
			<th>ID</th>
			<th>Status</th>
			<th>Created At</th>
			</tr>

			<% @zombie.tweets.each do |tweet| %>
				<tr>
				<td><%= tweet.id %></td>
				<td><%= tweet.status %></td>
				<td><%= tweet.created_at %></td>
				</tr>
			<% end %>

			</table>

		<% end %>

	</div>
</div>